<a href="https://colab.research.google.com/github/daria-pavlova/python_for_ds_tasks/blob/main/module_2.1/hw_2_1_4_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [ ]:
import numpy as np
import pandas as pd

1. numpy вектор vector розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1.

In [ ]:
random_vector = np.random.rand(10)
random_vector

array([0.72576557, 0.00411051, 0.32071442, 0.76632221, 0.51271667,
       0.59788753, 0.89644688, 0.10526675, 0.67335329, 0.7782725 ])

2. Матриця розмірності 3х3 з наданами значеннями.

In [ ]:
matrix = np.array( [[11, 14, 17],
                    [20, 23, 26],
                    [29, 32, 35]])
print("Матриця з наданими значеннями:")
print(matrix)

Матриця з наданими значеннями:
[[11 14 17]
 [20 23 26]
 [29 32 35]]



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


1. Додаванная до кожного елемента вектора і округлення до 2 знаків після коми.

In [ ]:
random_vector_addition_const = 10 + random_vector
random_vector_addition_const_rounded = np.round(random_vector_addition_const, 2)
random_vector_addition_const_rounded

array([10.73, 10.  , 10.32, 10.77, 10.51, 10.6 , 10.9 , 10.11, 10.67,
       10.78])

2. Множення кожного елементу матриці на 2.

In [ ]:
matrix_multi_const = 2 * matrix
matrix_multi_const

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

3. Квадрат для кожного елементу вектор без циклів.

In [ ]:
vector_expon_const = random_vector ** 2
print(vector_expon_const)

[5.26735656e-01 1.68962638e-05 1.02857738e-01 5.87249724e-01
 2.62878380e-01 3.57469503e-01 8.03617013e-01 1.10810892e-02
 4.53404657e-01 6.05708089e-01]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [ ]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

1. Множення матриць. Ми можемо перемножити ці матриці, бо кількість рядків першої матриці дорівнює кількості стовпчиків другої матриці.

In [ ]:
result = np.dot(A, B)
result_matrix = result[:2, :2]
result_matrix

array([[0.232 , 0.1627],
       [0.3061, 0.4867]])

2. Розмірність матриць після множення. Після множення матриці 2х2 на матрицю 2х1 результуюча матриця повинна бути розмірністю 2x1.

In [ ]:
np.dot(result_matrix, C)

array([[0.1627],
       [0.4867]])

3. Розмірність матриць після множення. Після множення матриці 2х2 на матрицю 2х1 результуюча матриця повинна бути розмірністю 2х2.

In [ ]:
result_matrix = np.dot(D, result_matrix)
result_matrix

array([[0.232 , 0.1627],
       [0.3061, 0.4867]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




1. Транспортування result_matrix.

In [ ]:
transported_result_matrix = np.transpose(result_matrix)
transported_result_matrix

array([[0.232 , 0.3061],
       [0.1627, 0.4867]])

2. Транспортування вектору. Порівнюючи результати різниці немає.

In [ ]:
transported_random_vector = np.transpose(random_vector)

print(random_vector)
print(transported_random_vector)

[0.72576557 0.00411051 0.32071442 0.76632221 0.51271667 0.59788753
 0.89644688 0.10526675 0.67335329 0.7782725 ]
[0.72576557 0.00411051 0.32071442 0.76632221 0.51271667 0.59788753
 0.89644688 0.10526675 0.67335329 0.7782725 ]


3. Результуючий вектор став масивом масивів у порівнянні зі звичайним масивом орігинального вектора.

In [ ]:
column_vector = np.expand_dims(random_vector, axis=1)
print(f"Column vector: \n {column_vector}")
print(f"Original vector: \n {random_vector}")

Column vector: 
 [[0.72576557]
 [0.00411051]
 [0.32071442]
 [0.76632221]
 [0.51271667]
 [0.59788753]
 [0.89644688]
 [0.10526675]
 [0.67335329]
 [0.7782725 ]]
Original vector: 
 [0.72576557 0.00411051 0.32071442 0.76632221 0.51271667 0.59788753
 0.89644688 0.10526675 0.67335329 0.7782725 ]


4. Транспортування column_vector призвело до того, що масив масивів став масивом в масиві. Розмірності перевернути 10х1 і 1х10.

In [ ]:
column_vector_transposed = np.transpose(column_vector)
print(f"Column vector:  \n {column_vector} and size: {column_vector.shape}")
print(f"Column vector transposed:  \n {column_vector_transposed} and size: {column_vector_transposed.shape}")

Column vector:  
 [[0.72576557]
 [0.00411051]
 [0.32071442]
 [0.76632221]
 [0.51271667]
 [0.59788753]
 [0.89644688]
 [0.10526675]
 [0.67335329]
 [0.7782725 ]] and size: (10, 1)
Column vector transposed:  
 [[0.72576557 0.00411051 0.32071442 0.76632221 0.51271667 0.59788753
  0.89644688 0.10526675 0.67335329 0.7782725 ]] and size: (1, 10)
